/**
 * Multiple-choice knapsack, solved exactly with dynamic programming.
 *
 * A direct port of `forneus_core.tools.amigatos.optimizer`. Two rules make the
 * port trustworthy, and both are pinned by `web/test/solver.test.ts` against
 * fixtures generated by the Python implementation:
 *
 *   1. Ties break toward the EARLIER option (`>` is strict, never `>=`), so a
 *      cheaper option of equal power wins.
 *   2. The chosen budget is the FIRST maximum, so leftover jelly is maximized.
 *
 * Typed arrays are what make this viable in a browser: the worst reachable
 * case (18 Red r2 just below the point where everything can be maxed) runs in
 * roughly 0.7 s here, against 0.9 s for numpy on a server.
 */

/** [cumulativeCost, effectivePower, rawPower, level] */
export type Option = [number, number, number, import('./dataset.ts').Level];

export interface Item {
  category: string;
  options: Option[];
}

export function solveKnapsack(items: Item[], budget: number): Option[] {
  const width = budget + 1;

  // Layer 0: no items chosen yet, so every budget is reachable with value 0.
  let previous = new Float64Array(width);
  const history: Int16Array[] = [];

  for (const { options } of items) {
    const current = new Float64Array(width).fill(-Infinity);
    const picked = new Int16Array(width);

    for (let index = 0; index < options.length; index++) {
      const cost = options[index][0];
      const power = options[index][1];
      if (cost > budget) continue;

      for (let capacity = cost; capacity < width; capacity++) {
        const candidate = previous[capacity - cost] + power;
        if (candidate > current[capacity]) {
          current[capacity] = candidate;
          picked[capacity] = index;
        }
      }
    }

    history.push(picked);
    previous = current;
  }

  let best = 0;
  for (let capacity = 1; capacity < width; capacity++) {
    if (previous[capacity] > previous[best]) best = capacity;
  }

  const chosen: Option[] = new Array(items.length);
  let capacity = best;
  for (let index = items.length - 1; index >= 0; index--) {
    const option = items[index].options[history[index][capacity]];
    chosen[index] = option;
    capacity -= option[0];
  }
  return chosen;
}

/**
 * Turn a level table into cumulative options, including staying at the base
 * level for no extra cost. Returns the mandatory entry cost separately: it is
 * paid per catpal regardless of how far it is leveled.
 */
export function cumulativeOptions(
  levels: { level: import('./dataset.ts').Level; bracket_cost: number; raw_power: number }[],
  rate: number,
): { options: Option[]; entryCost: number } {
  const [base] = levels;
  const options: Option[] = [[0, base.raw_power * rate, base.raw_power, base.level]];

  let cumulative = 0;
  for (let index = 1; index < levels.length; index++) {
    const row = levels[index];
    cumulative += row.bracket_cost;
    options.push([cumulative, row.raw_power * rate, row.raw_power, row.level]);
  }

  return { options, entryCost: base.bracket_cost };
}
