/**
 * "Keep or redistribute?" — the question a saved profile makes answerable.
 *
 * A direct port of `forneus_core.tools.amigatos.profiles`. Given the levels
 * each catpal is at today plus however much jelly you have earned since, it
 * compares two futures:
 *
 *   KEEP         spend only the new jelly, leaving current levels untouched.
 *   REDISTRIBUTE reset everything, reclaim what is invested, and re-solve the
 *                whole team from scratch with the full amount.
 *
 * Redistributing is not always better — the entry costs are paid again and
 * the solver may land on the same levels — which is exactly why it is worth
 * computing instead of guessing.
 *
 * Verified against `web/test/profile-fixtures.json`, generated by the Python
 * implementation.
 */
import { ToolError } from './errors.ts';
import { dataset, MAX_SAFE_BUDGET, MAX_TEAM_SIZE, type Level } from './dataset.ts';
import { cumulativeOptions, solveKnapsack, type Item, type Option } from './knapsack.ts';
import { solve } from './index.ts';

export interface ProfileCatpal {
  id: string;
  name?: string;
  catpal_type: string;
  current_level: Level;
}

export interface Profile {
  name?: string;
  catpals: ProfileCatpal[];
}

export interface Allocation {
  id: string;
  name: string;
  catpal_type: string;
  display_name: string;
  current_level: Level;
  target_level: Level;
  from_level: Level;
  to_level: Level;
  jelly_change: number;
  target_invested_jelly: number;
  raw_power: number;
  effective_power: number;
}

export interface Scenario {
  available_jelly: number;
  additional_jelly_spent: number;
  jelly_leftover: number;
  total_effective_power: number;
  total_raw_power: number;
  allocations: Allocation[];
  changes: Allocation[];
}

export interface ProfileComparison {
  profile_name: string;
  new_jelly: number;
  current: {
    invested_jelly: number;
    total_effective_power: number;
    total_raw_power: number;
    allocations: Allocation[];
  };
  keep: Scenario;
  redistribute: Scenario;
  recommendation: 'keep' | 'redistribute';
}

function levelsOf(key: string): Level[] {
  return dataset.categories[key].levels.map((row) => row.level);
}

function optionsOf(key: string) {
  const category = dataset.categories[key];
  return cumulativeOptions(category.levels, category.effectiveness_rate);
}

function validate(profile: Profile | null | undefined, newJelly: number): ProfileCatpal[] {
  if (!Number.isInteger(newJelly) || newJelly < 0 || newJelly > MAX_SAFE_BUDGET) {
    throw new ToolError('error.new_jelly.range', { max: MAX_SAFE_BUDGET });
  }
  if (!profile || !Array.isArray(profile.catpals)) {
    throw new ToolError('error.profile.shape');
  }
  const { catpals } = profile;
  if (catpals.length > MAX_TEAM_SIZE) {
    throw new ToolError('error.profile.too_large', { max: MAX_TEAM_SIZE });
  }

  const seen = new Set<string>();
  for (const catpal of catpals) {
    if (!catpal || typeof catpal !== 'object') throw new ToolError('error.profile.entry_shape');
    if (typeof catpal.id !== 'string' || !catpal.id) throw new ToolError('error.profile.id_missing');
    if (!(catpal.catpal_type in dataset.categories)) {
      throw new ToolError('error.category.unknown', { category: String(catpal.catpal_type) });
    }
    if (!levelsOf(catpal.catpal_type).includes(catpal.current_level)) {
      throw new ToolError('error.profile.level_invalid', {
        level: String(catpal.current_level),
        display_name: dataset.categories[catpal.catpal_type].display_name,
      });
    }
    if (catpal.name !== undefined && typeof catpal.name !== 'string') {
      throw new ToolError('error.profile.name_type');
    }
    if (seen.has(catpal.id)) throw new ToolError('error.profile.id_duplicated');
    seen.add(catpal.id);
  }
  return catpals;
}

/** Best option per item when everything is affordable; otherwise the full DP. */
function choose(items: Item[], budget: number): Option[] {
  const best = items.map(({ options }) =>
    options.reduce((a, b) => (b[1] > a[1] || (b[1] === a[1] && b[0] < a[0]) ? b : a)));
  return best.reduce((sum, option) => sum + option[0], 0) <= budget
    ? best
    : solveKnapsack(items, budget);
}

function allocationOf(catpal: ProfileCatpal, option: Option, jellyChange: number): Allocation {
  const [cost, effective, raw, level] = option;
  return {
    id: catpal.id,
    name: catpal.name ?? '',
    catpal_type: catpal.catpal_type,
    display_name: dataset.categories[catpal.catpal_type].display_name,
    current_level: catpal.current_level,
    target_level: level,
    from_level: catpal.current_level,
    to_level: level,
    jelly_change: jellyChange,
    target_invested_jelly: cost,
    raw_power: raw,
    effective_power: effective,
  };
}

export function optimizeProfile(
  profile: Profile | null | undefined,
  newJelly: number,
): ProfileComparison {
  const catpals = validate(profile, newJelly);

  const currentRows: Allocation[] = [];
  const currentAbsoluteCost = new Map<string, number>();
  const keepItems: Item[] = [];
  let currentInvested = 0;
  let currentEffective = 0;
  let currentRaw = 0;

  for (const catpal of catpals) {
    const { options, entryCost } = optionsOf(catpal.catpal_type);
    const index = options.findIndex((option) => option[3] === catpal.current_level);
    const current = options[index];
    const absolute = entryCost + current[0];

    currentAbsoluteCost.set(catpal.id, absolute);
    currentInvested += absolute;
    currentEffective += current[1];
    currentRaw += current[2];
    currentRows.push(allocationOf(catpal, current, 0));

    // Costs are rebased on today's level: staying put is free, and only the
    // steps still ahead cost anything.
    const incremental: Option[] = options.slice(index).map(
      ([cost, eff, raw, level]) => [cost - current[0], eff, raw, level]);
    keepItems.push({ category: catpal.id, options: incremental });
  }

  const keepChosen = keepItems.length ? choose(keepItems, newJelly) : [];
  const keepAllocations = catpals.map((catpal, index) => {
    const [delta, effective, raw, level] = keepChosen[index];
    const absolute = currentAbsoluteCost.get(catpal.id)! + delta;
    return allocationOf(catpal, [absolute, effective, raw, level], delta);
  });
  const keepSpent = keepAllocations.reduce((sum, a) => sum + a.jelly_change, 0);

  const keep: Scenario = {
    available_jelly: newJelly,
    additional_jelly_spent: keepSpent,
    jelly_leftover: newJelly - keepSpent,
    total_effective_power: keepAllocations.reduce((s, a) => s + a.effective_power, 0),
    total_raw_power: keepAllocations.reduce((s, a) => s + a.raw_power, 0),
    allocations: keepAllocations,
    changes: keepAllocations.filter((a) => a.target_level !== a.current_level),
  };

  // Redistributing assumes a full refund of what is already invested.
  const totalAfterRefund = currentInvested + newJelly;
  const counts: Record<string, number> = {};
  for (const catpal of catpals) {
    counts[catpal.catpal_type] = (counts[catpal.catpal_type] ?? 0) + 1;
  }
  const reset = solve(counts, totalAfterRefund);

  const targets = new Map<string, typeof reset.rows>();
  for (const row of reset.rows) {
    const list = targets.get(row.category) ?? [];
    list.push(row);
    targets.set(row.category, list);
  }

  const redistributed: Allocation[] = [];
  for (const key of Object.keys(dataset.categories)) {
    const order = levelsOf(key);
    const rank = (level: Level) => order.indexOf(level);
    // Pair lowest-with-lowest so nobody is told to move further than needed.
    const source = catpals.filter((c) => c.catpal_type === key)
      .sort((a, b) => rank(a.current_level) - rank(b.current_level));
    const target = (targets.get(key) ?? []).slice()
      .sort((a, b) => rank(a.level) - rank(b.level));

    source.forEach((catpal, index) => {
      const row = target[index];
      if (!row) return;
      const previous = currentAbsoluteCost.get(catpal.id)!;
      redistributed.push(allocationOf(
        catpal, [row.cost, row.effective_power, row.raw_power, row.level],
        row.cost - previous));
    });
  }

  const redistribute: Scenario = {
    available_jelly: totalAfterRefund,
    additional_jelly_spent: reset.totals.spent - currentInvested,
    jelly_leftover: reset.totals.leftover,
    total_effective_power: reset.totals.effective_power,
    total_raw_power: reset.totals.raw_power,
    allocations: redistributed,
    changes: redistributed.filter((a) => a.target_level !== a.current_level),
  };

  return {
    profile_name: profile?.name ?? '',
    new_jelly: newJelly,
    current: {
      invested_jelly: currentInvested,
      total_effective_power: currentEffective,
      total_raw_power: currentRaw,
      allocations: currentRows,
    },
    keep,
    redistribute,
    recommendation:
      redistribute.total_effective_power > keep.total_effective_power
        ? 'redistribute' : 'keep',
  };
}
