/**
 * The browser solver must agree with the Python core, case for case.
 *
 * `test/fixtures.json` is generated by `scripts/generate_fixtures.py` — it is
 * the Python implementation's own output. Python stays the reference; this
 * proves the port did not change a single number.
 *
 * Run with:  npm test
 * Regenerate after touching the tables or the solver:
 *     python scripts/generate_fixtures.py
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import { solve, ToolError, MAX_TEAM_SIZE } from '../src/lib/solver/index.ts';
import { dataset } from '../src/lib/solver/dataset.ts';

const fixtures = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures.json', import.meta.url)), 'utf8'),
);

/** Floats: the two languages must agree to well beyond display precision. */
function closeEnough(actual: number, expected: number, what: string) {
  assert.ok(Math.abs(actual - expected) < 1e-6,
    `${what}: TypeScript ${actual} != Python ${expected}`);
}

describe('paridade com o núcleo Python', () => {
  it('tem casos para comparar', () => {
    assert.ok(fixtures.cases.length >= 60, 'fixtures.json parece vazio ou truncado');
  });

  for (const testCase of fixtures.cases) {
    it(testCase.note, () => {
      const result = solve(testCase.input.counts, testCase.input.total_jelly);
      const expected = testCase.expected;

      for (const [key, value] of Object.entries(expected.totals) as [string, number][]) {
        closeEnough((result.totals as Record<string, number>)[key], value, `totals.${key}`);
      }

      assert.equal(result.rows.length, expected.rows.length, 'número de linhas');
      result.rows.forEach((row, index) => {
        const want = expected.rows[index];
        assert.equal(row.category, want.category, `linha ${index}: categoria`);
        assert.equal(row.level, want.level, `linha ${index}: nível`);
        assert.equal(row.cost, want.cost, `linha ${index}: custo`);
        closeEnough(row.effective_power, want.effective_power, `linha ${index}: poder`);
      });

      assert.deepEqual(result.notices, expected.notices, 'avisos');
    });
  }
});

describe('validação', () => {
  const invalid: [string, Record<string, number>, number][] = [
    ['categoria desconhecida', { Nope: 1 }, 100],
    ['quantidade negativa', { Purple: -1 }, 100],
    ['quantidade acima do limite', { Purple: 19 }, 100],
    ['quantidade fracionária', { Purple: 1.5 }, 100],
    ['equipe grande demais', { Purple: 10, RedR1: 9 }, 100],
    ['jelly negativa', { Purple: 1 }, -1],
    ['jelly fracionária', { Purple: 1 }, 1.5],
  ];

  for (const [note, counts, jelly] of invalid) {
    it(`rejeita ${note} com uma chave de tradução`, () => {
      assert.throws(() => solve(counts, jelly), (error: unknown) => {
        assert.ok(error instanceof ToolError, 'deve ser ToolError');
        assert.ok(error.key.startsWith('error.'), `chave estranha: ${error.key}`);
        return true;
      });
    });
  }
});

describe('limites de desempenho', () => {
  function ceiling() {
    return MAX_TEAM_SIZE * Math.max(...Object.values(dataset.categories)
      .map((c) => c.levels.reduce((sum, row) => sum + row.bracket_cost, 0)));
  }

  it('orçamento absurdo não vira trabalho', () => {
    const started = performance.now();
    const result = solve({ RedR2: MAX_TEAM_SIZE }, Number.MAX_SAFE_INTEGER);
    const elapsed = performance.now() - started;
    assert.ok(result.totals.leftover > 0);
    assert.ok(elapsed < 100, `levou ${elapsed.toFixed(0)}ms — o atalho quebrou`);
  });

  it('pior caso alcançável fica sub-segundo', () => {
    const started = performance.now();
    solve({ RedR2: MAX_TEAM_SIZE }, ceiling() - 1);
    const elapsed = performance.now() - started;
    console.log(`      pior caso: ${elapsed.toFixed(0)} ms`);
    assert.ok(elapsed < 5000, `levou ${elapsed.toFixed(0)}ms`);
  });
});
